export const defaultProperties = {
  translate: '0',
  rotate: '0deg',
  skew: '0deg',
  scale: '1',
  translate3d: '0',
  scale3d: '1, 1, 1',
  rotate3d: '0',
  'background-color': 'transparent',
  opacity: '1',
  'transform-origin': '0',
  perspective: '0',
  top: '0',
  right: '0',
  bottom: '0',
  left: '0',
  color: 'inherit',
  'font-size': 'medium',
  border: 'none',
  'border-radius': '0',
  'box-shadow': 'none',
};
